In [6]:

name ="Lizz"
print(name[0:2])

Li


In [11]:
A=(0, 1, 2, 3)
print(A[3])
print(A[-1])
print(A[1:])
A=(0, ("hello", "world"), 2, 3)
print(A[1][0])


3
3
(1, 2, 3)
hello


In [1]:
def Delta(x):
    if x==0:
        y=1;
    else:
        y=0;
    return(y)

print(Delta(0))
print(Delta(1))

1
0


In [10]:
x=[4,30,2,1]
print(x)
y=x.sort()
print(x)
print(y)

[4, 30, 2, 1]
[1, 2, 4, 30]
None


In [1]:
import numpy as np
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [4]:
a=np.array([0,1])

b=np.array([1,0])

c= np.dot(a,b)
c

np.int64(0)

In [5]:
a=np.array([1,1,1,1,1])

a+10 


array([11, 11, 11, 11, 11])

In [ ]:
# What is the correct code to perform matrix multiplication on the matrix A and B?
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
C

array([[19, 22],
       [43, 50]])

In [ ]:
# This is called the Hadamard product, which is element-wise multiplication of two arrays.
A*B

array([[ 5, 12],
       [21, 32]])

In [11]:
import pandas as pd

In [12]:
int(3.2)

3

In [13]:
A='1234567'

In [14]:
A[1::2]

'246'

In [15]:
F='hello world'
F.upper()

'HELLO WORLD'

In [16]:
 A=((11,12),[21,22])

In [17]:
A[0][1]

12

In [18]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [21]:
V={'A','B','C' }
V.add('C')
V

{'A', 'B', 'C'}

In [22]:
for n in range(3):
    print(n)

0
1
2


In [27]:
def Add(x,y):
    z=y+x
    return(y)
Add('1','1') 

'1'